package com.ibm.sso.common;

// Generated By AEF3 Framework, Powered by Dr.Adldoost :D
public enum BusinessExceptionCode {


    GENERAL_ERROR(-1),
    SECURITY_UNHANDLED_EXCEPTION(-2),
    JWT_PARSE_EXCEPTION(-3),
    INVALID_LOGIN_TOKEN(-4),
    ACCESS_DENIED(-5),

    NOT_VALID_DATA(2000),
    USER_ALREADY_EXISTS(2001),
    USERNAME_IS_REQUIRED(2002),
    PASSWORD_IS_REQUIRED(2003),
    USERNAME_IS_INVALID(2004),
    PASSWORD_IS_INVALID(2005),
    EMAIL_IS_INVALID(2006),
    EMAIL_IS_TAKEN_ALREADY(2007),
    USERNAME_IS_TAKEN_ALREADY(2008),
    USER_NOT_FOUND(2009),
    ROLE_NOT_FOUND(2010),

    COULD_NOT_CREATE_DIRECTORY(2011),
    COULD_NOT_STORED_FILE_RETRY(2012),

    FILE_NOT_FOUND_PATH(2013),



    //Validation
    BAD_INPUT(3000),
    ;

    private int value;

    public int getValue() {

        return this.value;

    }

    BusinessExceptionCode(int value) {

        this.value = value;

    }

    public static BusinessExceptionCode findByName(String name){
        for(BusinessExceptionCode v : values()){
            if( v.name() == name){
                return v;
            }
        }
        return null;
    }

}
