package com.ibm.sso.common;

// Generated By AEF3 Framework, Powered by Dr.Adldoost :D
public enum BusinessExceptionCode {


    GENERAL_ERROR(-1),
    SECURITY_UNHANDLED_EXCEPTION(-2),
    JWT_PARSE_EXCEPTION(-3),
    INVALID_LOGIN_TOKEN(-4),
    ACCESS_DENIED(-5),

    NOT_VALID_DATA(2000),


    //Validation
    BAD_INPUT(3000),
    ;

    private int value;

    public int getValue() {

        return this.value;

    }

    BusinessExceptionCode(int value) {

        this.value = value;

    }

    public static BusinessExceptionCode findByName(String name){
        for(BusinessExceptionCode v : values()){
            if( v.name() == name){
                return v;
            }
        }
        return null;
    }

}
