package com.ibm.sso.common;

// Generated By AEF3 Framework, powered by Dr.Adldoost :D
import java.util.Enumeration;
import java.util.ResourceBundle;

public class ErrorCodeReaderUtil {

    static ResourceBundle rb = ResourceBundle.getBundle("errorcodes");

    public static String getResourceProperity(String key)  {
            return rb.getString(key);

    }

    public static Enumeration<String> getResourceKeys(String key) {
            return rb.getKeys();
    }
}