package com.ibm.sso.common;

// Generated by AEF3 Framework, powered by Dr.Adldoost :D
import java.util.Random;

public class GenerateRandomStringUtil {

    public static String getSaltString(int lengh) {
        String SALTCHARS = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
        StringBuilder salt = new StringBuilder();
        Random rnd = new Random();
        while (salt.length() < lengh) { // length of the random string.
            int index = (int) (rnd.nextFloat() * SALTCHARS.length());
            salt.append(SALTCHARS.charAt(index));
        }
        String saltStr = salt.toString();
        return saltStr;

    }

}
