package com.ibm.sso.rest;

import com.aef3.data.SortUtil;
import com.aef3.data.api.qbe.SortObject;
import com.aef3.data.api.qbe.StringSearchType;
import com.ibm.sso.dto.SecurityPermissionDto;
import com.ibm.sso.dto.SecurityRoleDto;
import com.ibm.sso.service.SecurityRoleService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import com.ibm.sso.service.PagedResult;import java.util.Date;

import org.springframework.security.access.annotation.Secured;
import com.ibm.sso.security.AccessRoles;
import java.text.ParseException;
import java.util.Collections;
import java.util.List;


/* Generated By AEF Generator ( Powered by Dr.Adldoost :D ) */

@RestController
@RequestMapping("/security-role")
public class SecurityRoleRestService {

    private final SecurityRoleService securityRoleService;

    @Autowired
    public SecurityRoleRestService(SecurityRoleService securityRoleService) {
        this.securityRoleService = securityRoleService;
    }

    @Secured(AccessRoles.ROLE_FIND_SECURITY_ROLE)
    @GetMapping("/{id}")
    public SecurityRoleDto findById(@PathVariable(name = "id")Long id) {
        return securityRoleService.findByPrimaryKey(id);
    }

    @Secured(AccessRoles.ROLE_SEARCH_SECURITY_ROLE)
    @GetMapping("/search")
    public PagedResult search(
                                      @RequestParam(value = "name", required = false) String name,
                                      @RequestParam(value = "id", required = false) Long id,
                                      @RequestParam(value = "title", required = false) String title,
                                      @RequestParam(value = "firstIndex", required = false) Integer firstIndex,
                                      @RequestParam(value = "pageSize", required = false) Integer pageSize,
                                      @RequestParam(value = "sortField", required = false) String sortField,
                                      @RequestParam(value = "sortOrder", required = false) String sortOrder) {

            SortObject sortObject = SortUtil.generateSortObject(sortField, sortOrder);
            List<SortObject> sortObjectList = null;
            if(sortObject != null)
               sortObjectList = Collections.singletonList(sortObject);

            if(firstIndex == null)
               firstIndex = 0;
            if(pageSize == null)
               pageSize = Integer.MAX_VALUE;
            SecurityRoleDto securityRole = new SecurityRoleDto();
            securityRole.setName(name); 
            securityRole.setId(id); 
            securityRole.setTitle(title); 

            return securityRoleService.findPagedByExample(securityRole,
                   sortObjectList,
                   firstIndex,
                   pageSize,
                   StringSearchType.EXPAND_BOTH_SIDES,
                   null,
                   null
                   );
    }


    @Secured(AccessRoles.ROLE_SAVE_SECURITY_ROLE)
    @PostMapping(path = "/save")
    public SecurityRoleDto save(@RequestBody SecurityRoleDto securityRole) {
        return securityRoleService.save(securityRole);
    }


    @Secured(AccessRoles.ROLE_REMOVE_SECURITY_ROLE)
    @DeleteMapping(path = "/remove/{id}")
    public void remove(@PathVariable(name = "id")Long id) {
        securityRoleService.remove(id);
    }

    @GetMapping("/unassigned-permissions/{roleId}")
    public List<SecurityPermissionDto> findUnAssignedPermissionsForRole(@PathVariable(name = "roleId")Long roleId) {
        return securityRoleService.findUnAssignedPermissionsForRole(roleId);
    }
}