package com.ibm.sso.model;

import com.aef3.data.api.DomainEntity;

import javax.persistence.*;
import java.util.Date;
import java.util.List;
import java.util.Objects;


/* Generated By AEF Generator ( Powered by Dr.Adldoost :D ) */

@Entity
@Table(name = "security_user")
public class SecurityUser implements DomainEntity {


    @Column(name = "last_login")
    @Temporal(TemporalType.TIMESTAMP)
    private Date lastLogin;

    @Column(name = "password", nullable = false, length = 512)
    private String password;

    @Column(name = "suspension_code", length = 8)
    private String suspensionCode;

    @Column(name = "mobile", length = 13)
    private String mobile;

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "failure_count")
    private Integer failureCount;

    @Column(name = "email", length = 100)
    private String email;

    @Column(name = "username", nullable = false, length = 100)
    private String username;

    @Column(name = "status")
    private Integer status;

    @Column(name = "creation_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date creationDate;


    @JoinTable(name = "sec_user_role",
            joinColumns = {@JoinColumn(name = "user", referencedColumnName = "id", nullable = false)}
            , inverseJoinColumns = {@JoinColumn(name = "role", referencedColumnName = "id", nullable = false)})
    @ManyToMany(cascade = CascadeType.ALL)
    private List<SecurityRole> roleList;

    @ManyToMany(mappedBy = "userList", cascade = CascadeType.ALL)
    private List<SecurityPermission> permissionList;



    public Date getLastLogin() {
        return lastLogin;
    }

    public void setLastLogin(Date lastLogin) {
       this.lastLogin = lastLogin;
    }


    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
       this.password = password;
    }


    public String getSuspensionCode() {
        return suspensionCode;
    }

    public void setSuspensionCode(String suspensionCode) {
       this.suspensionCode = suspensionCode;
    }


    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
       this.mobile = mobile;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
       this.id = id;
    }


    public Integer getFailureCount() {
        return failureCount;
    }

    public void setFailureCount(Integer failureCount) {
       this.failureCount = failureCount;
    }


    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
       this.email = email;
    }


    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
       this.username = username;
    }


    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
       this.status = status;
    }

    public List<SecurityRole> getRoleList() {
        return roleList;
    }

    public void setRoleList(List<SecurityRole> roleList) {
        this.roleList = roleList;
    }

    public List<SecurityPermission> getPermissionList() {
        return permissionList;
    }

    public void setPermissionList(List<SecurityPermission> permissionList) {
        this.permissionList = permissionList;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SecurityUser)) return false;
        SecurityUser securityUser = (SecurityUser) o;
        return Objects.equals(id, securityUser.id);
    }

    @Override
    public int hashCode() {

        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "SecurityUser{" +
                "id=" + id +
                '}';
    }
}