package com.ibm.sso.model;

import com.aef3.data.api.DomainEntity;

import javax.persistence.*;
import java.util.Date;
import java.util.List;
import java.util.Objects;


/* Generated By AEF Generator ( Powered by Dr.Adldoost :D ) */

@Entity
@Table(name = "security_permission")
public class SecurityPermission implements DomainEntity {


    @Column(name = "name", nullable = false, length = 100)
    private String name;

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "title", nullable = false, length = 200)
    private String title;

    @JoinTable(name = "sec_role_permission", joinColumns = {
            @JoinColumn(name = "sec_permission", referencedColumnName = "id", nullable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "sec_role", referencedColumnName = "id", nullable = false)})
    @ManyToMany(cascade = CascadeType.ALL)
    private List<SecurityRole> roleList;

    @JoinTable(name = "sec_user_permission", joinColumns = {
            @JoinColumn(name = "sec_permission", referencedColumnName = "id", nullable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "sec_user", referencedColumnName = "id", nullable = false)})
    @ManyToMany(cascade = CascadeType.ALL)
    private List<SecurityUser> userList;



    public String getName() {
        return name;
    }

    public void setName(String name) {
       this.name = name;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
       this.id = id;
    }


    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
       this.title = title;
    }

    public List<SecurityRole> getRoleList() {
        return roleList;
    }

    public void setRoleList(List<SecurityRole> roleList) {
        this.roleList = roleList;
    }

    public List<SecurityUser> getUserList() {
        return userList;
    }

    public void setUserList(List<SecurityUser> userList) {
        this.userList = userList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SecurityPermission)) return false;
        SecurityPermission securityPermission = (SecurityPermission) o;
        return Objects.equals(id, securityPermission.id);
    }

    @Override
    public int hashCode() {

        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "SecurityPermission{" +
                "id=" + id +
                '}';
    }
}