package com.ibm.sso.dto;

import com.aef3.data.api.DomainDto;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.ibm.sso.model.FileObject;

import java.util.Date;


/* Generated By AEF Generator ( Powered by Dr.Adldoost :D ) */

public class FileObjectDto implements DomainDto<FileObject, FileObjectDto> {


    private String path;
    private String name;
    private String description;
    private Long id;
    private String title;
    private String roleObject;
    private String md5;
    private Date uploadDate;

    public FileObjectDto() {
    }


    public String getPath() {
        return path;
    }
    public void setPath(String path) {
        this.path = path;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }

    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    public String getRoleObject() {
        return roleObject;
    }
    public void setRoleObject(String roleObject) {
        this.roleObject = roleObject;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public Date getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    public static FileObjectDto toDto(FileObject fileObject) {

        if(fileObject == null)
            return null; 
        FileObjectDto dto = new FileObjectDto();
        dto.setPath(fileObject.getPath());
        dto.setName(fileObject.getName());
        dto.setDescription(fileObject.getDescription());
        dto.setId(fileObject.getId());
        dto.setTitle(fileObject.getTitle());
        dto.setRoleObject(fileObject.getRoleObject());
        dto.setUploadDate(fileObject.getUploadDate());
        return dto;
  }


    public static FileObject toEntity(FileObjectDto dto) {

        if(dto == null)
            return null; 
        FileObject file = new FileObject();
        file.setPath(dto.getPath());
        file.setName(dto.getName());
        file.setDescription(dto.getDescription());
        file.setId(dto.getId());
        file.setTitle(dto.getTitle());
        file.setRoleObject(dto.getRoleObject());
        file.setUploadDate(dto.getUploadDate());
        return file;
  }
    @Override
    public FileObject toEntity() {
        return FileObjectDto.toEntity(this);
    }

    @JsonIgnore
    @Override
    public FileObjectDto getInstance(FileObject fileObject) {
        return FileObjectDto.toDto(fileObject);
    }

    @JsonIgnore
    @Override
    public FileObjectDto getInstance() {
        return new FileObjectDto();
    }
}