package com.ibm.sso.jwt;

import java.util.Date;
import java.util.List;

/**
 *
 * @author Generated By AEF3 Frameword, powered by Dr.Adldoost :D
 */
public class JWTUserDetails {

    private String username;
    private Date creationDate;
    private List<String> roles;
    private List<String> permissions;


    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public List<String> getRoles() {
        return roles;
    }

    public void setRoles(List<String> roles) {
        this.roles = roles;
    }
    public List<String> getPermissions() {
        return permissions;
    }

    public void setPermissions(List<String> permissions) {
        this.permissions = permissions;
    }
}
