package com.ibm.sso.jwt;

// Generated By AEF3 Framework, powered by Dr.Adldoost :D
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Repository;
import java.util.Calendar;
import java.util.Date;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

@Repository
@Scope(value = ConfigurableBeanFactory.SCOPE_SINGLETON)
public class TokenRepository {

    private Map<String, Date> tokenMap = new ConcurrentHashMap<>();

    public void put(String username, Date date) {
        tokenMap.put(username, date);
    }

    public Date getTokenIssueDate(String username) {
        return tokenMap.get(username);
    }

    public void invalidateUserToken(String username) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(new Date());
        cal.add(Calendar.SECOND, 2);
        tokenMap.put(username, cal.getTime());
    }
}