package com.ibm.sso.dao;

import com.aef3.data.impl.AbstractDAOImpl;
import com.ibm.sso.model.FileObject;
import org.springframework.stereotype.Repository;


/* Generated By AEF Generator ( Powered by Dr.Adldoost :D ) */

@Repository
public class FileDao extends AbstractDAOImpl<FileObject, Long> {

    public FileDao() {
        super(FileObject.class);
    }
}