package com.ibm.sso.dao;

import com.aef3.data.impl.AbstractDAOImpl;
import com.ibm.sso.model.MenuItem;
import org.springframework.stereotype.Repository;

import java.util.List;


/* Generated By AEF Generator ( Powered by Dr.Adldoost :D ) */

@Repository
public class MenuItemDao extends AbstractDAOImpl<MenuItem, Long> {

    public MenuItemDao() {
        super(MenuItem.class);
    }

    public List<MenuItem> findRootItems() {

        return getEntityManager().createQuery("select i from MenuItem i where i.parentItem is null ", MenuItem.class)
                .getResultList();
    }
}