package com.ibm.sso.dao;

import com.aef3.data.impl.AbstractDAOImpl;
import com.ibm.sso.model.SecurityPermission;
import org.springframework.stereotype.Repository;


/* Generated By AEF Generator ( Powered by Dr.Adldoost :D ) */

@Repository
public class SecurityPermissionDao extends AbstractDAOImpl<SecurityPermission, Long> {

    public SecurityPermissionDao() {
        super(SecurityPermission.class);
    }
}