package com.ibm.sso.dao;

import com.aef3.data.impl.AbstractDAOImpl;
import com.ibm.sso.model.SecurityUser;
import org.springframework.stereotype.Repository;


/* Generated By AEF Generator ( Powered by Dr.Adldoost :D ) */

@Repository
public class SecurityUserDao extends AbstractDAOImpl<SecurityUser, Long> {

    public SecurityUserDao() {
        super(SecurityUser.class);
    }
}