package com.ibm.sso.dao;

import com.aef3.data.impl.AbstractDAOImpl;
import com.ibm.sso.common.BusinessExceptionCode;
import com.ibm.sso.model.SecurityPermission;
import com.ibm.sso.model.SecurityRole;
import com.ibm.sso.model.SecurityUser;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;


/* Generated By AEF Generator ( Powered by Dr.Adldoost :D ) */

@Repository
public class SecurityUserDao extends AbstractDAOImpl<SecurityUser, Long> {

    private SecurityPermissionDao securityPermissionDao;
    private SecurityRoleDao securityRoleDao;

    @Autowired
    public SecurityUserDao(SecurityPermissionDao securityPermissionDao, SecurityRoleDao securityRoleDao) {
        super(SecurityUser.class);
        this.securityPermissionDao = securityPermissionDao;
        this.securityRoleDao = securityRoleDao;
    }

    public SecurityUser findUserByUsernameOrEmail(String username, String email) {

        List<SecurityUser> securityUserList = getEntityManager().createQuery("select su from SecurityUser su where " +
                "su.username = :username or su.email = :email", SecurityUser.class)
                .setParameter("username", username)
                .setParameter("email", email)
                .setMaxResults(1)
                .getResultList();
        if(securityUserList != null && !securityUserList.isEmpty()) {
            return securityUserList.get(0);
        }
        return null;
    }

    public List<SecurityPermission> findUnAssignedPermissionsForUser(Long userId) {

        SecurityUser securityUser = findByPrimaryKey(userId);

        if(securityUser == null)
            throw new RuntimeException(BusinessExceptionCode.USER_NOT_FOUND.name());

        if(securityUser.getPermissionList() != null && !securityUser.getPermissionList().isEmpty())
            return getEntityManager().createQuery("select p from SecurityPermission p where " +
                "p not in :permissionList", SecurityPermission.class)
                .setParameter("permissionList", securityUser.getPermissionList())
                .getResultList();
        else
            return getEntityManager().createQuery("select p from SecurityPermission p", SecurityPermission.class)
            .getResultList();
    }

    public List<SecurityRole> findUnAssignedRolesForUser(Long userId) {

        SecurityUser securityUser = findByPrimaryKey(userId);

        if(securityUser == null)
            throw new RuntimeException(BusinessExceptionCode.USER_NOT_FOUND.name());

        if(securityUser.getRoleList() != null && !securityUser.getRoleList().isEmpty())
            return getEntityManager().createQuery("select r from SecurityRole r where " +
                    "r not in :roleList", SecurityRole.class)
                    .setParameter("roleList", securityUser.getRoleList())
                    .getResultList();
        else
            return getEntityManager().createQuery("select r from SecurityRole r", SecurityRole.class)
                    .getResultList();
    }

    public SecurityUser addPermissionsToUser(List<Long> permissionIdList, Long userId) {

        if(permissionIdList == null || permissionIdList.isEmpty())
            return findByPrimaryKey(userId);
        SecurityUser securityUser = findByPrimaryKey(userId);
        if(securityUser == null)
            throw new RuntimeException(BusinessExceptionCode.USER_NOT_FOUND.name());
        if(securityUser.getPermissionList() == null)
            securityUser.setPermissionList(new ArrayList<>());
        permissionIdList.stream().forEach(p -> {
            SecurityPermission securityPermission = securityPermissionDao.findByPrimaryKey(p);
            securityUser.getPermissionList().add(securityPermission);
        });
        return save(securityUser);
    }

    public SecurityUser addRolesToUser(List<Long> roleIdList, Long userId) {

        if(roleIdList == null || roleIdList.isEmpty())
            return findByPrimaryKey(userId);
        SecurityUser securityUser = findByPrimaryKey(userId);
        if(securityUser == null)
            throw new RuntimeException(BusinessExceptionCode.USER_NOT_FOUND.name());
        if(securityUser.getRoleList() == null)
            securityUser.setRoleList(new ArrayList<>());
        roleIdList.stream().forEach(p -> {
            SecurityRole securityRole = securityRoleDao.findByPrimaryKey(p);
            securityUser.getRoleList().add(securityRole);
        });
        return save(securityUser);
    }

    public SecurityUser removeRoleFromUser(Long roleId, Long userId) {

        SecurityUser securityUser = findByPrimaryKey(userId);
        if(securityUser == null)
            throw new RuntimeException(BusinessExceptionCode.USER_NOT_FOUND.name());
        if(securityUser.getRoleList() == null || securityUser.getRoleList().isEmpty())
            return securityUser;
        SecurityRole securityRole = securityRoleDao.findByPrimaryKey(roleId);
        if(securityRole == null)
            throw new RuntimeException(BusinessExceptionCode.BAD_INPUT.name());
        securityUser.getRoleList().remove(securityRole);
        return save(securityUser);
    }

    public SecurityUser removePermissionFromUser(Long permissionId, Long userId) {

        SecurityUser securityUser = findByPrimaryKey(userId);
        if(securityUser == null)
            throw new RuntimeException(BusinessExceptionCode.USER_NOT_FOUND.name());
        if(securityUser.getPermissionList() == null || securityUser.getPermissionList().isEmpty())
            return securityUser;
        SecurityPermission securityPermission = securityPermissionDao.findByPrimaryKey(permissionId);
        if(securityPermission == null)
            throw new RuntimeException(BusinessExceptionCode.BAD_INPUT.name());
        securityUser.getPermissionList().remove(securityPermission);
        return save(securityUser);
    }
}