package com.ibm.sso.dao;

import com.aef3.data.impl.AbstractDAOImpl;
import com.ibm.sso.model.SecurityRole;
import org.springframework.stereotype.Repository;


/* Generated By AEF Generator ( Powered by Dr.Adldoost :D ) */

@Repository
public class SecurityRoleDao extends AbstractDAOImpl<SecurityRole, Long> {

    public SecurityRoleDao() {
        super(SecurityRole.class);
    }
}