package com.ibm.sso.dao;

import com.aef3.data.impl.AbstractDAOImpl;
import com.ibm.sso.model.WebPage;
import org.springframework.stereotype.Repository;


/* Generated By AEF Generator ( Powered by Dr.Adldoost :D ) */

@Repository
public class WebPageDao extends AbstractDAOImpl<WebPage, Long> {

    public WebPageDao() {
        super(WebPage.class);
    }
}