package com.ibm.sso.service;


import com.aef3.data.Filter;
import com.aef3.data.api.DomainDto;
import com.aef3.data.api.qbe.CompareObject;
import com.aef3.data.api.qbe.RangeObject;
import com.aef3.data.api.qbe.SortObject;
import com.aef3.data.api.qbe.StringSearchType;


import java.io.Serializable;
import java.util.List;

/**
 *
 * @author Generated by AEF3 Framework, powered by Dr.Adldoost :D 
 * @param <D>
 * @param <PK>
 */
public interface GeneralService<D extends DomainDto, PK extends Serializable> {

    List<D> paginate(Filter<D> filter);

    D save(D entity);

    void save(List<D> entities);
//
//    void create(D t);
//
//    void edit(D t);

    void remove(PK id);

    void bulkRemove(List<PK> entityIdList);

    List<D> findByExample(D example, List<SortObject> sortObjectList, int startIndex, int pageSize, StringSearchType searchType);

    List<D> findByExample(D example, int startIndex, int pageSize, StringSearchType searchType);

    List<D> findByExample(D example);

    List<D> findByExample(D example, List<SortObject> sortObjectList);

    List<D> findByExample(D example, List<SortObject> sortObjectList, StringSearchType searchType);

    List<D> findByExample(D example, List<SortObject> sortObjectList, int startIndex, int pageSize, StringSearchType searchType, List<RangeObject> rangeObjectList);

    List<D> findByExample(D example, List<SortObject> sortObjectList, int startIndex, int pageSize, StringSearchType searchType, List<RangeObject> rangeObjectList, List<CompareObject> comparableList);

    List<D> findByExample(D example, List<SortObject> sortObjectList, StringSearchType searchType, List<RangeObject> rangeObjectList);

    List<D> findByExample(D example, StringSearchType searchType);

    D findSingleByExample(D example, List<SortObject> sortObjectList, StringSearchType searchType);

    D findSingleByExample(D example, List<SortObject> sortObjectList);

    D findSingleByExample(D example, StringSearchType searchType);

    D findSingleByExample(D example);

    long countByExample(D example, StringSearchType searchType);

    void removeByExample(D example, StringSearchType searchType);

    D findByPrimaryKey(PK primaryKey);

    D getDtoInstance();

    PagedResult<D> findPagedByExample(D example, List<SortObject> sortObjectList, int startIndex, int pageSize, StringSearchType searchType, List<RangeObject> rangeObjectList, List<CompareObject> compareObjects);

    Long countByExample(D example, StringSearchType searchType, List<RangeObject> rangeObjectList, List<CompareObject> compareObjects);
}
